language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
  - pip install coveralls
script: 
  - python setup.py test
  - coverage run --source=metatool setup.py test
after_success: coveralls
